### ISSUE TITLE
Errors on v3.0.2 upgrade

### ISSUE THREAD

**Issue by stanlog** [arawa/workspace#874]
Hello,
I tried to upgrade workspace to v3.0.2 this morning, this upgrade broke my instance (errors, maintenance mode)

Nextcloud : 25.0.8
DB : Postgresql

```
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <workspace> ...
An unhandled exception has been thrown:
ParseError: syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE) in /var/www/xxxxxx.fr/apps/workspace/lib/Migration/ChangeGroupnamesV300.php:40
Stack trace:
#0 /var/www/xxxxxx.fr/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 [internal function]: spl_autoload_call()
#3 /var/www/xxxxxr.fr/lib/private/AppFramework/Utility/SimpleContainer.php(114): ReflectionClass->__construct()
#4 /var/www/xxxxx.fr/lib/private/AppFramework/Utility/SimpleContainer.php(134): OC\AppFramework\Utility\SimpleContainer->resolve()
#5 /var/www/xxxxxfr/lib/private/AppFramework/DependencyInjection/DIContainer.php(466): OC\AppFramework\Utility\SimpleContainer->query()
#6 /var/www/xxxxx.fr/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#7 /var/www/xxxxx.fr/lib/private/AppFramework/Utility/SimpleContainer.php(57): OC\ServerContainer->query()
#8 /var/www/xxxxx.fr/lib/private/Repair.php(144): OC\AppFramework\Utility\SimpleContainer->get()
#9 /var/www/xxxxxx.fr/lib/private/legacy/OC_App.php(1061): OC\Repair->addStep()
#10 /var/www/xxxxx.fr/lib/private/legacy/OC_App.php(1005): OC_App::executeRepairSteps()
#11 /var/www/xxxxx.fr/lib/private/Updater.php(361): OC_App::updateApp()
#12 /var/www/xxxxxxx.fr/lib/private/Updater.php(273): OC\Updater->doAppUpgrade()
#13 /var/www/xxxxxx.fr/lib/private/Updater.php(141): OC\Updater->doUpgrade()
#14 /var/www/xxxxxx.fr/core/Command/Upgrade.php(225): OC\Updater->upgrade()
#15 /var/www/xxxxxx.fr/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#16 /var/www/xxxxxx.fr/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#17 /var/www/xxxxxx.fr/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#18 /var/www/xxxxxx.fr/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#19 /var/www/xxxxxx.fr/lib/private/Console/Application.php(214): Symfony\Component\Console\Application->run()
#20 /var/www/xxxxxx.fr/console.php(100): OC\Console\Application->run()
#21 /var/www/xxxxxx.fr/occ(11): require_once('/var/www/cloud....')
```

I disabled the app waiting for a solution.
Thank you for your help.

**Comment by smarinier** [comment]
Hi, i think this is due to PHP 8.0 requirement. Could you upgrade your PHP version on your server ? NextCloud 25 is the last version supporting (but deprecated) PHP 7.4. But PHP 8.1 is recommended.

**Comment by zak39** [comment]
Hi @stanlog 

As @smarinier says, it is recommended to use PHP8.X and not PHP7.X : https://github.com/arawa/workspace#from-nextcloud-25.

Which version of PHP are you using ?

**Comment by zak39** [comment]
Hi @stanlog , Is your problem solved ?

**Comment by zak39** [comment]
Hi @stanlog ,

I haven't received your response to this issue.

I consider this issue resolved and I close it.
If needed, I can reopen it.

Thanks for your report 🙏
